
package SOAP.AdmpReplay.wsdl;

import jakarta.xml.ws.*;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.2
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "AdmpReplay", targetNamespace = "http://gibdd.ru", wsdlLocation = "file:/home/nick/IdeaProjects/projectStandart/src/main/resources/wsdl/SOAP.AdmpReplay.wsdl")
public class AdmpReplay
    extends Service
{

    private final static URL ADMPREPLAY_WSDL_LOCATION;
    private final static WebServiceException ADMPREPLAY_EXCEPTION;
    private final static QName ADMPREPLAY_QNAME = new QName("http://gibdd.ru", "AdmpReplay");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/home/nick/IdeaProjects/projectStandart/src/main/resources/wsdl/SOAP.AdmpReplay.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        ADMPREPLAY_WSDL_LOCATION = url;
        ADMPREPLAY_EXCEPTION = e;
    }

    public AdmpReplay() {
        super(__getWsdlLocation(), ADMPREPLAY_QNAME);
    }

    public AdmpReplay(WebServiceFeature... features) {
        super(__getWsdlLocation(), ADMPREPLAY_QNAME, features);
    }

    public AdmpReplay(URL wsdlLocation) {
        super(wsdlLocation, ADMPREPLAY_QNAME);
    }

    public AdmpReplay(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, ADMPREPLAY_QNAME, features);
    }

    public AdmpReplay(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public AdmpReplay(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns AdmpReplaySoap
     */
    @WebEndpoint(name = "AdmpReplaySoap")
    public AdmpReplaySoap getAdmpReplaySoap() {
        return super.getPort(new QName("http://gibdd.ru", "AdmpReplaySoap"), AdmpReplaySoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns AdmpReplaySoap
     */
    @WebEndpoint(name = "AdmpReplaySoap")
    public AdmpReplaySoap getAdmpReplaySoap(WebServiceFeature... features) {
        return super.getPort(new QName("http://gibdd.ru", "AdmpReplaySoap"), AdmpReplaySoap.class, features);
    }

    private static URL __getWsdlLocation() {
        if (ADMPREPLAY_EXCEPTION!= null) {
            throw ADMPREPLAY_EXCEPTION;
        }
        return ADMPREPLAY_WSDL_LOCATION;
    }

}
