
package SOAP.AdmpReplay.wsdl;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.2
 * Generated source version: 2.2
 * 
 */
@WebService(name = "AdmpReplaySoap", targetNamespace = "http://gibdd.ru")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface AdmpReplaySoap {


    /**
     * 
     * @param pFatherName
     * @param pStartDate
     * @param pFamily
     * @param pName
     * @param pOGRN
     * @param pBirtdhDate
     * @param pINN
     * @return
     *     returns SOAP.AdmpReplay.wsdl.Result
     */
    @WebMethod(operationName = "GetDataFIO", action = "http://gibdd.ru/SOAP.AdmpReplay.GetDataFIO")
    @WebResult(name = "GetDataFIOResult", targetNamespace = "http://gibdd.ru")
    @RequestWrapper(localName = "GetDataFIO", targetNamespace = "http://gibdd.ru", className = "SOAP.AdmpReplay.wsdl.GetDataFIO")
    @ResponseWrapper(localName = "GetDataFIOResponse", targetNamespace = "http://gibdd.ru", className = "SOAP.AdmpReplay.wsdl.GetDataFIOResponse")
    public Result getDataFIO(
        @WebParam(name = "pFamily", targetNamespace = "http://gibdd.ru")
        String pFamily,
        @WebParam(name = "pName", targetNamespace = "http://gibdd.ru")
        String pName,
        @WebParam(name = "pFatherName", targetNamespace = "http://gibdd.ru")
        String pFatherName,
        @WebParam(name = "pBirtdhDate", targetNamespace = "http://gibdd.ru")
        String pBirtdhDate,
        @WebParam(name = "pOGRN", targetNamespace = "http://gibdd.ru")
        String pOGRN,
        @WebParam(name = "pStartDate", targetNamespace = "http://gibdd.ru")
        XMLGregorianCalendar pStartDate,
        @WebParam(name = "pINN", targetNamespace = "http://gibdd.ru")
        String pINN);

}
